// Generates .env with a session secret on first run, so a fresh clone can
// `pnpm dev` immediately. src/server/session.ts throws without SESSION_SECRET.
import { existsSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';

if (existsSync('.env')) process.exit(0);

writeFileSync(
  '.env',
  `# Generated by scripts/setup-env.mjs. Not committed.\n` +
    `SESSION_SECRET=${randomBytes(32).toString('base64')}\n`,
);
console.log('Created .env with a fresh SESSION_SECRET.');
